### PR TITLE
Redesign of client HTTP context APIs

### PR DESCRIPTION
**Pull request by ok2c**
* Aligns client context APIs with those in core
* Context classes are now plain beans
* Backward compatibility with older versions (through internal Delegate classes)
* Javadoc imprvements

### CODE REVIEW

**Comment by ok2c** [comment]
@arturobernalg Please take a look.

**Review by arturobernalg — APPROVED** [review]
@ok2c 
LGTM

**Comment by sratz** [comment]
This change is incompatible.

Consider when a *consumer* sets the attributes on the context:

```java
BasicCookieStore cookieStore = new BasicCookieStore();
HttpClientContext context = new HttpClientContext();
context.setAttribute(HttpClientContext.COOKIE_STORE, cookieStore); // <----
CloseableHttpClient client = HttpClients.createDefault();
client.execute(new HttpGet("https://httpbin.org/cookies/set/foo/bar"), context, response -> null);
System.out.println(cookieStore.getCookies());
```

httpclient < 5.4 correctly uses the request-specific cookie store and prints:
```[[name: foo; value: bar; domain: httpbin.org; path: /; expiry: null]]```

httpclient 5.4 does not care about the attribute anymore ([diff](https://github.com/apache/httpcomponents-client/pull/552/files#diff-16278c1c7854154453531a554fbcaf624a76d7b6ca1e95eb529148f361fd9348R179-R180)) and prints:
```[]```

Switching from
```
context.setAttribute(HttpClientContext.COOKIE_STORE, cookieStore);
```
to
```
context.setCookieStore(cookieStore);
```
does not solve the problem, as that would work in 5.4, but not in 5.3 anymore.

The only chance I see to support both is to do *both*
```
context.setAttribute(HttpClientContext.COOKIE_STORE, cookieStore);
context.setCookieStore(cookieStore);
```

Shouldn't this have been compatible? I.e. ([here](https://github.com/apache/httpcomponents-client/pull/552/files#diff-16278c1c7854154453531a554fbcaf624a76d7b6ca1e95eb529148f361fd9348R179-R180)), consider *both* the getter and the attribute?

**Comment by ok2c** [comment]
> does not solve the problem, as that would work in 5.4, but not in 5.3 anymore.

@sratz  Why would not that work in 5.3?

**Comment by sratz** [comment]
> > does not solve the problem, as that would work in 5.4, but not in 5.3 anymore.
> 
> @sratz Why would not that work in 5.3?

Because there the reverse is true, `org.apache.hc.client5.http.impl.classic.InternalHttpClient.setupContext(HttpClientContext)` only looks at the attributes, not at the getter methods:
https://github.com/apache/httpcomponents-client/blob/4f852608c3315975bf6cd72d10999626784cd9a6/httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/InternalHttpClient.java#L123-L138

**Comment by sratz** [comment]
I think the problem is that `HttpClientContext` never kept the well-known named attributes and their equivalent object member in sync, i.e.

`setAttribute("http.cookie-store", ...)` and `setCookieStore()` have always referred to two completely independent things.

**Comment by ok2c** [comment]
> only looks at the attributes, not at the getter methods:

@sratz `context.setCookieStore(cookieStore);` will work correctly regardless of the version. What changed in 5.4 is that standard attributes no longer get shoved into a map.

**Comment by sratz** [comment]
> @sratz `context.setCookieStore(cookieStore);` will work correctly regardless of the version. What changed in 5.4 is that standard attributes no longer get shoved into a map.

Ok, you're right.

However, there's still a breaking change that the string-based attributes are now not considered at all anymore in 5.4. So they are not just deprecated.

**Pull request merged**
