### PR TITLE
Refactor testcase

### PR DESCRIPTION
**Pull request by niranjanghule**
Remove unused variable.

### CODE REVIEW

**Comment by ok2c** [comment]
@niranjanghule I am not a big fan of such one-line commits. Is this the only instance of an unused variable in the source code?

**Comment by niranjanghule** [comment]
Hi Oleg,

I have not analyzed entire codebase.
I was studying few testcases and raised pr only for those.

Thanks and Regards
Niranjan Ghule
MOB: 9867061576

**Comment by ok2c** [comment]
@niranjanghule I am not a big fan of one-line refactoring commits. I will make an exception in this case, though

**Comment by niranjanghule** [comment]
Thanks! I'll avoid single line commits next time onwards.

Thanks and Regards
Niranjan Ghule

**Pull request merged**
