### PR TITLE
HTTPCLIENT-751:  Support for RFC 2817 (Upgrading to TLS Within HTTP/1.1)

### PR DESCRIPTION
**Pull request by ok2c**
This change-set adds support for an optional upgrade to TLS of HTTP/1.1 connections through `Upgrade` / `Switch-Protocol` handshake

### CODE REVIEW

**Comment by ok2c** [comment]
@arturobernalg Please take a look.

**Comment by arturobernalg** [comment]
> @arturobernalg Please take a look.

@ok2c .  I just need a couple of days to thoroughly read and understand RFC 2817 to ensure my feedback is well-informed

**Comment by ok2c** [comment]
> > @arturobernalg Please take a look.
> 
> @ok2c . I just need a couple of days to thoroughly read and understand RFC 2817 to ensure my feedback is well-informed

@arturobernalg You do not need to do that unless you want to. It would be sufficient to take a look and the changes and see if there is anything that looks obviously wrong or crazy.

**Review by arturobernalg — APPROVED** [review]
@ok2c 
LGTM. I now have a clear understanding of the RFC and the proposed changes.

**Comment by bplotnick** [comment]
This caused https://issues.apache.org/jira/browse/HTTPCLIENT-2344

**Pull request merged**
