### PR TITLE
HTTPCLIENT-2186 - Migrate Test to Unit 5.

### PR DESCRIPTION
**Pull request by arturobernalg**
The first approach of the change to Junit 5

### CODE REVIEW

**Review by ok2c — APPROVED** [review]

**Comment by timtebeek** [comment]
Noticed you're using `@EnableRuleMigrationSupport` to retain `@RunWith(Parameterized.class)`.
Are you aware of [this automated JUnit Jupiter migration for Parameterized](https://docs.openrewrite.org/reference/recipes/java/testing/junit5/parameterizedrunnertoparameterized) using OpenRewrite?
They even have [a full migration that you can apply](https://docs.openrewrite.org/tutorials/migrate-from-junit-4-to-junit-5).

**Comment by ok2c** [comment]
> Noticed you're using `@EnableRuleMigrationSupport` to retain `@RunWith(Parameterized.class)`. Are you aware of [this automated JUnit Jupiter migration for Parameterized]

@timtebeek I did attempt to port our parameterized tests to JUnit 5 approximately 6 months back and failed. There was simply no way (I could find or think of) to parameterize resource rules with JUnit 5.

Any chance you could upgrade just one test case to demonstrate how it can be done?

**Comment by timtebeek** [comment]
Oh wow yes it's quite a bit more involved; looked into it just now, but the whole hierarchy down from `org.apache.hc.client5.testing.async.AbstractServerTestBase` is a challenge given that scheme is now passed as a constructor argument. No quick fixes there I'm afraid. :disappointed:

**Comment by arturobernalg** [comment]
> Oh wow yes it's quite a bit more involved; looked into it just now, but the whole hierarchy down from `org.apache.hc.client5.testing.async.AbstractServerTestBase` is a challenge given that scheme is now passed as a constructor argument. No quick fixes there I'm afraid. 😞

Hi @timtebeek I tried different things and  was impossible.
TY

**Pull request merged**
