### PR TITLE
Httpclient 2044 reuse immutables

### PR DESCRIPTION
**Pull request by garydgregory**
[HTTPCLIENT-2044] Don't create stateless/immutable factory objects.

### CODE REVIEW

**Comment by michael-o** [comment]
For my understanding, every client instance  has its own factory instances, Client are thread-safe, so must be those factory instances. Therefore, they are safe to be shared among client instances?

**Comment by garydgregory** [comment]
All of the classes for which I created a DEFAULT or INSTANCE are stateless and defined as `@Contract(threading = ThreadingBehavior.STATELESS)`. I think it would be better to doc some of these as immutable instead of stateless, but it's a detail.

**Comment by michael-o** [comment]
Looking into...

**Comment by michael-o** [comment]
Rebased, let's wait for the test results.

**Comment by garydgregory** [comment]
Thanks @michael-o

**Pull request merged**
