### PR TITLE
URIBuilder extended for new method for empty values

### PR DESCRIPTION
**Pull request by CanardSauvage**
We are using the URIBuilder heavily across many projects. Before this we had our only implementation of an 'UrlBuilder' but we changed every usage to the URIBuilder. There is only one method missing - we add a lot of parameters, but sometimes they are not set/ empty/ null.

So this method would really help us to keep urls short and to not add unnecessary parameters.

### CODE REVIEW

**Comment by michael-o** [comment]
Having parameters with blank values is perfectly fine. Why do we need another method for that where you can do a `StringUtils.isEmpty` for that?

**Comment by CanardSauvage** [comment]
Because you would need to do an if with StringUtils.isEmpty for every parameter. We build a lot of urls for redirects and for links with a lot of parameters. If we had blank values the urls would be longer and they are already really long. Or the code would be uglier and longer.

**Comment by ok2c** [comment]
Sebastian 
We cannot commit this patch to 4.5.x due to its changing the API signature of URIBuilder. There is unlikely to ever be a 4.6 series so this change can be applied to trunk (5.0) only.

Having said that I also find this new method of a marginal use outside of your specific case

**Comment by CanardSauvage** [comment]
Well, the pull request is against the trunk, so it would be applied to 5.0, or am I wrong?

I don't think this is a specific use case. In my opinion the builder would be more complete with this method. If you are building an url and add a lot of parameters (from your session, user data, ...) you would prefer this method instead of the normal addParameter-method. Normally I would prefer for this behaviour to be the default, but giving the option to add empty keys is also valid.

**Comment by michael-o** [comment]
You are responsible for *your* data and we for the proper URL building.

**Comment by CanardSauvage** [comment]
Maybe complete is the wrong word. The class is for proper URL building and this is a convenience method that helps to reduce code. It would make the class easier to use, so why not add this method?

As explained, there are two possibilities - you want to build an url and you don't want empty values or you want more control and you want to explicitly add only the key. But this does not really matter if you can give the user the possibility for both with two methods - so he can choose what he exactly wants.

**Comment by michael-o** [comment]
I'd rather see a boolean parameter at the end, not another method name.

**Comment by wThomas84** [comment]
Hi, I think its the discussion about a convenience method here that might simplify adoption and usage of this utility class.
Another parameter adds complexity to the existing method, which is not quite shorter than the solution proposed for just another method, having a specific, easy-to-understand scope and behavior.

**Comment by ok2c** [comment]
I am fine with committing the patch to the trunk (5.0). Michael, do you think?

**Comment by michael-o** [comment]
@ok2c I'll have a look at it tomorrow again.

**Comment by michael-o** [comment]
@CanardSauvage as most folks are used to Commons Lang with `StringUtils#isEmpty`, the method shall be named `add...NotEmpty`. I would still prefer method overloading with a boolean parameter.

@ok2c Please have a look ath the test case, line 160. This does not look like a valid URI to me. As per RFC 3986, spaces are encoded with a space sign and not plus sign. This is form encoded. Is that a bug in the URI builder? I'd rather go for standards-compliance in 5.0.

**Comment by ok2c** [comment]
@michael-o Yes, that is the case. URIBuilder has not been reviewed for RFC 3986 conformance.

**Comment by CanardSauvage** [comment]
@michael-o Boolean parameters are an anti pattern, cf. Clean Code

I changed the name.

**Comment by CanardSauvage** [comment]
What is the status, we would be really happy if this method mades it into the next release.

**Pull request closed without merging**
