### PR TITLE
activate SCM publish to /httpcomponents-client-5.0.x/doc/

### PR DESCRIPTION
**Pull request by hboutemy**
you can either put that as a branch to do tests, either directly in master given it's not a revolution

@michael-o

### CODE REVIEW

**Comment by ok2c** [comment]
@hboutemy Could you please re-spit this PR?

**Comment by hboutemy** [comment]
done
with this branch, you can/should
```
mvn clean site site:stage
mvn scm-publish:publish-scm
```
and look at the result at https://hc.apache.org/httpcomponents-client-5.0.x/doc/

**Comment by ok2c** [comment]
Thank you, @hboutemy. What is the plan now? Are we supposed to publish versioned reports to https://hc.apache.org/httpcomponents-<module>-<version>/doc/ and then reference them from the main website project as URLs?

**Comment by hboutemy** [comment]
for now deploy the current SNAPSHOT, test, see the result, discuss before deciding

**Comment by ok2c** [comment]
@hboutemy Could you please make the same changes to httpcore, as it is more likely to have a release soon?

**Comment by hboutemy** [comment]
please publish to https://hc.apache.org/httpcomponents-client-5.0.x/doc/ and review before we test somewhere else
and I'm sure there will be improvements to discuss before talking about release (which means: content of the release will never change)

**Comment by ok2c** [comment]
@hboutemy  I reviewed the staged site and it looked OK to me. I do not see any need for further improvements as far as content is concerned but admittedly I only care about javadocs and clirr (JCmpApi) reports.

**Comment by hboutemy** [comment]
- I suppose the whole team is interested
- there is the discussion about unversioned vs versioned
- there is more than javadoc and clirr

**Pull request merged**
