### PR TITLE
Added decorateRedirectExec to HttpClientBuilder

### PR DESCRIPTION
**Pull request by Blackmorse**
Ability to retry redirected requests, as described here

https://stackoverflow.com/questions/67565624/apache-http-client-retries-with-redirect

### CODE REVIEW

**Comment by ok2c** [comment]
@Blackmorse Should not we rather change the sequence of request interceptors?

**Comment by ok2c** [comment]
> > @Blackmorse Should not we rather change the sequence of request interceptors?
> 
> First redirect and then retry?

@michael-o Pretty much.

**Comment by Blackmorse** [comment]
> Should not we rather change the sequence of request interceptors?

I guess this can broke clients who relies on old behaviour..

**Comment by michael-o** [comment]
> 
> 
> > Should not we rather change the sequence of request interceptors?
> 
> I guess this can broke clients who relies on old behaviour..

I am quite certain that people aren't of that and we, AFAIR, we don't document the order explicitly.

**Comment by ok2c** [comment]
> > > Should not we rather change the sequence of request interceptors?
> > 
> > 
> > I guess this can broke clients who relies on old behaviour..
> 
> I am quite certain that people aren't aware of that and we, AFAIR, we don't document the order explicitly.

@michael-o Agreed. 

@Blackmorse Could you please test the change locally and re-spin the PR? 

Alternatively we can change the sequence of interceptors in 5.2 and keep the old behavior in all stable branches (4.5.x, 5.0.x and 5.1.x).

**Comment by Blackmorse** [comment]
> Alternatively we can change the sequence of interceptors in 5.2 and keep the old behavior in all stable branches (4.5.x, 5.0.x and 5.1.x).

Ok, I will take a look at this

**Pull request closed without merging**
