### PR TITLE
HTTPCLIENT-2079 - Remove the timestamp property.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Review by ok2c — APPROVED** [review]

**Comment by michael-o** [comment]
@arturobernalg Please rebase again on top of maste and I will merge.

**Comment by arturobernalg** [comment]
> @arturobernalg Please rebase again on top of maste and I will merge.



> @arturobernalg Please rebase again on top of maste and I will merge.

rebased
Ty

**Comment by michael-o** [comment]
@ok2c Any objections to backport this to 5.1.x and 5.0.x? It would be consistent with the corresponding branches in Core 5.

**Comment by ok2c** [comment]
@michael-o Not at all.

**Pull request closed without merging**
