### PR TITLE
4.5.x deduplicate redundant immutable objects

### PR DESCRIPTION
**Pull request by garydgregory**
Reuse singleton instances of immutable instances.

Static singletons finals are called INSTANCE when there is only one instance possible and DEFAULT when more than one instance can be constructed with parameters.

### CODE REVIEW

**Comment by michael-o** [comment]
I wouldn't touch 4.x anymore with so many changes.

**Comment by ok2c** [comment]
@garydgregory I agree with @michael-o I would not touch 4.x any longer beyond major bug fixes unless we want to initiate 4.6.x development cycle.

**Comment by garydgregory** [comment]
Hi All,
I respectfully disagree for the following reason with the side note that I do not care if we use this in a 4.5.x or 4.6.x:
Most of the code path in the software stacks I work with use HC 4. I've managed to migrate a small pile of code to HC 5 (good for me) and I plan for new projects to use HC 5. But, for the foreseeable future, HC 4 is going to live in my software stacks, either directly or transitively, there is no way around that, my team and I just maintain and develop a lot of code. While not perfect or desirable, I must consider for my team both HC 4 and HC 5 as active for now. Yes, eventually HC 5 will be everywhere for me, but not now, and not this year even, who knows when.

**Comment by michael-o** [comment]
@garydgregory We have a huge product by Siemens PLM which used Commons HttpClient 3. x until last year. ;-)
I understand that you want to have code consistent if possible. I would propose to release 4.5.x if there are unreleased changes. Create branch 4.6.x and re-review this PR for this new branch.

**Pull request closed without merging**
