### PR TITLE
Make some package protected classes public as we need to extend them in current jmeter

### PR DESCRIPTION
**Pull request by pmouawad**
Hello,
Would it be possible to make those classes public as for now in JMeter, to use validation mechanism introduced in 4.3 we had to create a custom class located in  package "org.apache.http.impl.conn" which is clearly a hack.
In the future we will probably migrate directly to HttpClient5.

Thanks

### CODE REVIEW

**Comment by fxbonnet** [comment]
Hi,
It looks like these classes are deprecated. I think the best way for you to implement your validation mechanism would be to create a subclass of org.apache.http.pool.AbstractConnPool

**Comment by ok2c** [comment]
+1 to @fxbonnet's comment

**Comment by pmouawad** [comment]
@ok2c , @fxbonnet , I am aware of the fact that classes are deprecated, see how we use them and the javadocs:

- https://github.com/apache/jmeter/blob/trunk/src/protocol/http/org/apache/http/impl/conn/JMeterPoolingClientConnectionManager.java

Doing what you propose means for me  copy/pasting the 3 classes in JMeter, which I don't find it better.
Migrating fully to 4.5 new code is identified:

- https://bz.apache.org/bugzilla/show_bug.cgi?id=58757

Still, the migration is not a little piece of cake and for us does not bring enough ROI to be done.
JMeter relied on "advanced" api of HC4 and although I know you make a lot of effort, documentation for migration was not complete at all for such parts.

@ok2c helped a lot on Cookie migration which was important feature for us. We're using new APIs for new code , like Async Backend Listener that interracts with InfluxDB, but as you know we have to make some choice as time is not infinite :-) 

In the future and if possible, it would be nice when you deprecate an API to mention in javadoc its new class equivalent. It's not done everywhere.

As Http2 is expected in 5.0, for now I must say I prefer to do migration at that time.

But @ok2c  if you don't want to merge the PR, I'll do that.

**Comment by ok2c** [comment]
@pmouawad I'll happily help with the migration (either to 4.5 or 5.0 depending on your preference) but opening up deprecated APIs looks wrong to me.

**Comment by pmouawad** [comment]
@ok2c , thanks for your proposal. I understand. As I have seen some PR on deprecated API (SNI retro fix) I thought it was possible.

I'll be very happy if you can help on migration. 5.0 being in alpha mode for now, do you think we should wait for migration or migrate already to more up to date API of 4.5.X ? Will it reduce the amount of work at end ?

Thanks

**Comment by ok2c** [comment]
@pmouawad it is one thing to back-port a fix or a feature that has no API impact but this is a whole different thing to start opening up private methods. 
It will take a while for 5.0 to mature. It really depends if you want to migrate early and have influence on API development or prefer convenience of API stable releases.

**Pull request closed without merging**
