### PR TITLE
4.5.x (org.apache.http.impl.client)HttpRequestTaskCallable

### PR DESCRIPTION
**Pull request by chenying99**
metrics.getRequests().increment(started);
                metrics.getTasks().increment(started);//这里应该是scheduled
                metrics.getActiveConnections().decrementAndGet();

line 106,  "started" should be "scheduled"? 
yes or no?

### CODE REVIEW

**Comment by ok2c** [comment]
@chenying99 _please_ **close** this pull request! It drags in 181 unrelated commits. Please close this pull request or reduce the change-set just to those changes you are proposing.

**Comment by ok2c** [comment]
@chenying99 Please close this PR.

**Comment by perlun** [comment]
@chenying99 seems to have left the building. @ok2c, could you just close it perhaps?

**Comment by ok2c** [comment]
@perlun Sadly, I cant. I have read only access to the project hosted at GitHub. Only select folks at ASF Infra can do that.

**Comment by perlun** [comment]
@ok2c 

> @perlun Sadly, I cant. I have read only access to the project hosted at GitHub. Only select folks at ASF Infra can do that.

I see. Maybe @sebbASF has access or know someone who has?

**Comment by ok2c** [comment]
@perlun I seriously doubt he would care. The right way to deal with the problem is to raise a JIRA with ASF Infra and kindly ask them to close the PR for us (and a few others).

**Comment by perlun** [comment]
@ok2c 

> The right way to deal with the problem is to raise a JIRA with ASF Infra and kindly ask them to close the PR for us (and a few others).

Makes sense. Feel free to do it, I'm just a (mostly) innocent bystander. :innocent:

**Pull request closed without merging**
