### PR TITLE
Refactor ExponentialBackoffManager Tests to Remove Thread.sleep().

### PR DESCRIPTION
**Pull request by arturobernalg**
This PR refactors the unit tests for `ExponentialBackoffManager` to remove the use of Thread.sleep(), making the tests more reliable and faster.

### CODE REVIEW

**Comment by ok2c** [comment]
@arturobernalg 

I just saw this error with the latest code in one of my CI runs. Could you please take a look at it as well?

```
[INFO] Running org.apache.hc.client5.http.impl.classic.TestLinearBackoffManager
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in org.apache.hc.client5.http.impl.classic.TestLinearBackoffManager
Error:  org.apache.hc.client5.http.impl.classic.TestLinearBackoffManager.backoffDoesNotAdjustDuringCoolDownPeriod  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <5> but was: <6>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:629)
	at org.apache.hc.client5.http.impl.classic.TestLinearBackoffManager.backoffDoesNotAdjustDuringCoolDownPeriod(TestLinearBackoffManager.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

**Comment by arturobernalg** [comment]
> @arturobernalg
> 
> I just saw this error with the latest code in one of my CI runs. Could you please take a look at it as well?
> 
> ```
> [INFO] Running org.apache.hc.client5.http.impl.classic.TestLinearBackoffManager
> Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in org.apache.hc.client5.http.impl.classic.TestLinearBackoffManager
> Error:  org.apache.hc.client5.http.impl.classic.TestLinearBackoffManager.backoffDoesNotAdjustDuringCoolDownPeriod  Time elapsed: 0.002 s  <<< FAILURE!
> org.opentest4j.AssertionFailedError: expected: <5> but was: <6>
> 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
> 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
> 	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
> 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
> 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
> 	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:629)
> 	at org.apache.hc.client5.http.impl.classic.TestLinearBackoffManager.backoffDoesNotAdjustDuringCoolDownPeriod(TestLinearBackoffManager.java:88)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```

HI @ok2c 
I've adjusted the `backoffDoesNotAdjustDuringCoolDownPeriod` test to better simulate the cool-down period by manipulating the `lastRouteBackoffs` map. 

TY

**Comment by ok2c** [comment]
@arturobernalg What about TestLinearBackoffManager?

**Comment by arturobernalg** [comment]
> TestLinearBackoffManager

@ok2c 
Was modify a couple day before [5c61b0a](https://github.com/apache/httpcomponents-client/commit/5c61b0ae975ce6e439e97a0d77ba283f8189a0cd) but i didn't have updated  my branch.

**Comment by ok2c** [comment]
> > TestLinearBackoffManager
> 
> @ok2c Was modify a couple day before [5c61b0a](https://github.com/apache/httpcomponents-client/commit/5c61b0ae975ce6e439e97a0d77ba283f8189a0cd) but i didn't have updated my branch.

@arturobernalg I am afraid the test case still fails intermittently _with_ your latest changes. We can leave it for now and see how often the failure occurs (if at all)

**Review by ok2c — APPROVED** [review]

**Pull request merged**
