### PR TITLE
Update the method parameter from String to CharSequence.

### PR DESCRIPTION
**Pull request by wangkaish**
Update the method parameter of InetAddressUtils from String to CharSequence.

Sometimes I need to pass parts of a String to this method instead of splitting the String into multiple pieces.

### CODE REVIEW

**Comment by garydgregory** [comment]
@wangkaish 
You'll need to _add_ tests that exercise CharSequence parameter values.

**Comment by wangkaish** [comment]
Hi @garydgregory 
String is an implementation of CharSequence, and the test argument used in TestInetAddressUtils is String, so I don't think we need a test case with a CharSequence argument anymore.

**Comment by garydgregory** [comment]
Changing the API from a class to an interface has no such behavioral guarantee, even if the API binary compatibility is maintained. 

IOW there is no proof that the methods actually work with known implementing clases like CharBuffer, StringBuffer, StringBuilder, and so on.

**Comment by ok2c** [comment]
@wangkaish There will be no more changes to 4.5.x. Please port the proposed change-set to `master`.

**Comment by wangkaish** [comment]
@ok2c ok, InetAddressUtils moved to httpcomponents-core, I will create a new pr to httpcomponents-core and close this pr.

**Pull request closed without merging**
