### PR TITLE
Safely remove unnecessary unboxing. No need it after Java 5 and later.

### PR DESCRIPTION
**Pull request by arturobernalg**
Sorry for so many stupid changes. I'm checking the cache module as was suggest in the mailing list.

### CODE REVIEW

**Review by carterkozak — APPROVED** [review]
looks good to me.

**Comment by garydgregory** [comment]
-1 for me: unboxing makes it obvious where wrappers are used and forced one to consider when NPEs might be thrown.

**Comment by arturobernalg** [comment]
> -1 for me: unboxing makes it obvious where wrappers are used and forces one to consider when NPEs might be thrown.

HI @garydgregory 
I thing your 

> unboxing

This Unboxing has't prevent the PNE.  At lest this one. The NPE will  produce before of this.

**Comment by ok2c** [comment]
@arturobernalg Generally, not useful and applied to a single class, not consistently across the entire code base. 
Generally all stylistic changes are  _not_ useful unless they are backed by a style check or a commonly agreed upon style-guide applied consistently throughout the code base. Please find something more useful to work on. 

Agree with @garydgregory about autoboxing hiding possible NPEs.

**Comment by arturobernalg** [comment]
Would be better validate the result. Not spect a NPE

` Args.notNull(result, "Completed Result");`

**Comment by ok2c** [comment]
@arturobernalg Still not useful, unless done consistently throughout the entire code base.

**Pull request closed without merging**
