### PR TITLE
HTTPCLIENT-2277 - Remove Warning header and stale handling in accordance with RFC9111

### PR DESCRIPTION
**Pull request by arturobernalg**
In compliance with the updates in RFC9111, this commit removes all uses of the Warning header and checks for staleness in cached entries.

RFC9111 obsoletes the use of the Warning header, noting that much of its information can be gleaned from other header fields. In practice, the Warning header was rarely added by caches or intermediaries, and the remaining information, although potentially useful, was entirely advisory. Consequently, all instances of the Warning header have been removed from the codebase.

Similarly, in the previous RFC7234, there was a requirement to handle stale cache entries and revalidate them, but this is no longer required in RFC9111. Hence, stale checks and revalidation have also been removed.

Appropriate log messages have been added where necessary to ensure important events and potential issues are still recorded.

### CODE REVIEW

**Comment by ok2c** [comment]
@arturobernalg I am sorry I was not keeping you up to date about I have been working on while on vacation. I actually implemented a similar change in my private branch [1] along with removal of other outdated / deprecated functionality. Could you please take a look at my branch and let me know if you prefer to commit your change-set or merge my branch first? 

[1] https://github.com/ok2c/httpcomponents-client/tree/HTTPCLIENT-2277

**Comment by arturobernalg** [comment]
> 

Checking

**Comment by arturobernalg** [comment]
> @arturobernalg I am sorry I was not keeping you up to date about I have been working on while on vacation. I actually implemented a similar change in my private branch [1] along with removal of other outdated / deprecated functionality. Could you please take a look at my branch and let me know if you prefer to commit your change-set or merge my branch first?
> 
> [1] https://github.com/ok2c/httpcomponents-client/tree/HTTPCLIENT-2277

@ok2c 
checking.

**Comment by arturobernalg** [comment]
@ok2c 
 I prefer go with you're branch.
TY

**Pull request closed without merging**
