### PR TITLE
HTTPCLIENT-2051

### PR DESCRIPTION
**Pull request by ok2c**

### CODE REVIEW

**Comment by awwright** [comment]
@michael-o et al. I don't know where to report this, but I think this isn't quite right; 303 must _always_ be changed to GET, regardless of the request method. Whereas for 301/302, the method _may_ be changed from POST only (if so configured for historical reasons).

**Comment by ok2c** [comment]
> @michael-o et al. I don't know where to report this, but I think this isn't quite right; 303 must _always_ be changed to GET, regardless of the request method. Whereas for 301/302, the method _may_ be changed from POST only (if so configured for historical reasons).

@awwright RFC 7231, `6.4.4. 303 See Other` does not seem support it. Is there anything I may have overlooked?

**Comment by michael-o** [comment]
@ok2c See here for details: https://github.com/curl/curl/issues/5237

**Comment by michael-o** [comment]
@ok2c, I think we need to review the direct handling for 5.1.x. Make it fully compliant and provide a "historic" version with POST to GET in 301/302.

**Comment by ok2c** [comment]
@michael-o Where does HttpClient 5.0 still deviate from RFC 723*? I actually made quite an effort to make 5.0 fully compliant with RFC 723*.

**Comment by michael-o** [comment]
@ok2c I did not say it deviates. I am just saying that we need to types of redirect strategies or or a flexible one to cover all cases from this RFC.

**Comment by ok2c** [comment]
@michael-o Fair enough.
@awwright I am going to change 303 handling in 5.0.x by making it always redirect as `GET` for all methods

**Comment by ok2c** [comment]
@awwright @michael-o Please see 7e2ea15

**Comment by michael-o** [comment]
@ok2c Looks good to me. I wonder why `SC_TEMPORARY_REDIRECT` and `SC_PERMANENT_REDIRECT` are not covered at all.

**Comment by ok2c** [comment]
> @ok2c Looks good to me. I wonder why `SC_TEMPORARY_REDIRECT` and `SC_PERMANENT_REDIRECT` are not covered at all.

@michael-o Those are newer status codes that do not imply any method conversion
```
6.4.3. 302 Found
...
Note: For historical reasons, a user agent MAY change the request
method from POST to GET for the subsequent request. If this
behavior is undesired, the 307 (Temporary Redirect) status code
can be used instead.
```

**Comment by michael-o** [comment]
That's not what I meant. I meant that we should handle both. Old and new status codes. As for the old ones, we should also support modern behavior as well as historic behavior.

**Comment by ok2c** [comment]
@michael-o The current behavior (with 7e2ea15 applied) is fully compliant with RFC 723*. If we want to add new methods to `RedirectStrategy` we could do it in 5.1 but it would likely require upgrade to Java 1.8. I personally not sure it is worth it.

**Comment by michael-o** [comment]
How does the upgrade to Java 8 correlate to the `RedirectStrategy`? I am confused.

**Comment by awwright** [comment]
> I am going to change 303 handling in 5.0.x by making it always redirect as `GET` for all methods

Yeah, I should have clarified, the current behavior for 301/302 looks OK; it's 303 that always performs a GET (or HEAD) request, even for methods besides POST.

**Comment by ok2c** [comment]
> How does the upgrade to Java 8 correlate to the `RedirectStrategy`? I am confused.

@michael-o One would need support for default methods to modify `RedirectStrategy` interface without breaking binary compatibility, would not one?

**Comment by michael-o** [comment]
Yes, you are right. I completely forgot this. But aren't we breaking binary compat anyway by upgrading to Java 8? Why would we then require default methods in this case?

**Comment by ok2c** [comment]
> Yes, you are right. I completely forgot this. But aren't we breaking binary compat anyway by upgrading to Java 8? 

No, we are not. Binaries compiled against 5.0 APIs with Java 1.7 will require no recompilation when running with 5.1 binary and Java 1.8  

> Why would we then require default methods in this case?

How would add a new method to an existing interface otherwise?

**Comment by michael-o** [comment]
> 
> 
> > Yes, you are right. I completely forgot this. But aren't we breaking binary compat anyway by upgrading to Java 8?
> 
> No, we are not. Binaries compiled against 5.0 APIs with Java 1.7 will require no recompilation when running with 5.1 binary and Java 1.8
> 
> > Why would we then require default methods in this case?
> 
> How would add a new method to an existing interface otherwise?

You are absolutely right, on both points. Let's but the change of the `RedirectStrategy` interface back for a moment. I'd focus to add 307 and 308 to `RedirectExec`. The should should cover > 90% of all cases.

**Pull request merged**
