### PR TITLE
Build requests from method names

### PR DESCRIPTION
**Pull request by garydgregory**
Now that ClassicHttpRequests is no longer an enum, I need to way to generically build requests from method names.

### CODE REVIEW

**Comment by michael-o** [comment]
Will look at it later...

**Comment by ok2c** [comment]
@garydgregory @michael-o Please make symmetric changes to `BasicHttpRequests` and `SimpleHttpRequests`.

**Comment by garydgregory** [comment]
> @garydgregory @michael-o Please make symmetric changes to `BasicHttpRequests` and `SimpleHttpRequests`.

I'll do that in a separate PR now that @michael-o has approved this one.

**Comment by ok2c** [comment]
@garydgregory Why? Why separate PR?

**Comment by garydgregory** [comment]
> @garydgregory Why? Why separate PR?

@michael-o had approved the PR. I feel it is nicer _not_ to ask a reviewer to look at the same code _again_

**Comment by ok2c** [comment]
@garydgregory It was nicer to merge half-baked change-set? How so? The reviewer might still need to look at the remaining changes before the entire change-set gets merged.

**Pull request merged**
