### PR TITLE
Allow to add exec interceptor as the first and the last

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to OpenTracing integration #74 and https://issues.apache.org/jira/browse/HTTPCLIENT-1842?focusedCommentId=15996807&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15996807 

cc @ok2c

### CODE REVIEW

**Comment by ok2c** [comment]
Looks good to me. Could you please do the same for the async client builder?

**Comment by pavolloffay** [comment]
Last/first interceptor added to the `AsyncClient`.

**Comment by pavolloffay** [comment]
When is going the release of 5.0 happen?

**Comment by ok2c** [comment]
HttpClient 5.0-alpha2 vote is ongoing.

**Comment by pavolloffay** [comment]
> That seems quite reasonable. Some unit tests would be nice as well.

@garydgregory Could you please point me to existing tests for `HttpClientBuilder#addExecInterceptorBefore` and its alternatives? I wasn't able to find them.

> HttpClient 5.0-alpha2 vote is ongoing.

When is the GA planned for? I have to look at async client, what is necessary for tracing.

**Comment by garydgregory** [comment]
I do not see any either . You can be the first ;-)

HttpCore 5 GA has to come first. Oleg can speak to schedule. I think it will be a while though. We are in alpha mode.

**Comment by pavolloffay** [comment]
Could it go in without tests? I don't know how the test should look like. 

To implement tests I need to access `NamedElementChain<ExecChainHandler>` which is constructed inside `HttpClientBuilder.build()`. I could define a new property with a package visibility getter in the builder, but it's not so nice.

**Comment by ok2c** [comment]
@pavolloffay Please bear with me a few more days. I'll merge your changes as soon as we are done migrating to Git

**Comment by ok2c** [comment]
@pavolloffay The PR got automatically closed as a result of migration from svn to git. I'll get it merged anyway

**Comment by pavolloffay** [comment]
@ok2c thanks!

**Pull request closed without merging**
