### PR TITLE
Minor Improvement:

### PR DESCRIPTION
**Pull request by arturobernalg**
* Avoid duplicate code
* Simplify if else
* Inline variables

### CODE REVIEW

**Comment by ok2c** [comment]
@arturobernalg If you really want to log those exceptions should they be logged at the ERROR priority?

**Comment by arturobernalg** [comment]
> @arturobernalg If you really want to log those exceptions should they be logged at the ERROR priority?

Hi @ok2c 

IMO We should inform in somewhere that's an error occurs. What about a warning?

**Comment by ok2c** [comment]
@arturobernalg I would even use DEBUG priority. Could you please take `Add log Catch` out of this patch and put it into a separate PR for now?

**Comment by arturobernalg** [comment]
> @arturobernalg I would even use DEBUG priority. Could you please take `Add log Catch` out of this patch and put it into a separate PR for now?

HI @ok2c 

agree. We can talk about the LOG.XX by mail or later. removed from PR

**Pull request merged**
