### PR TITLE
Logs improvements:

### PR DESCRIPTION
**Pull request by arturobernalg**
* Use just log4j-api.
* Rename libs to log4j2.
* Bump version slf4j 1.7.32.

### CODE REVIEW

**Comment by arturobernalg** [comment]
HI @michael-o 
Could you mind check this change pls.
TY

**Comment by ok2c** [comment]
@arturobernalg Those are _test_ dependencies! Please _do not_ do that!.

**Comment by arturobernalg** [comment]
> @arturobernalg Those are _test_ dependencies! Please _do not_ do that!.

But we don't need the log4j-core in the http api.
slf4j it's just and update.
and the rename is IMO its coherent with Log4j[](https://logging.apache.org/log4j/2.x/)

**Comment by ok2c** [comment]
@arturobernalg Those are TEST dependencies! They are NOT part of the API!

**Pull request closed without merging**
