### PR TITLE
[HTTPCLIENT-1952] Allow default User Agent to be disabled

### PR DESCRIPTION
**Pull request by michael-o**
Naive approach works for me. I am not certain whether the `@see` is necessary. I think not.

### CODE REVIEW

**Comment by thc202** [comment]
It seems you didn't commit all changes (`defaultUserAgentDisabled` is not used).

**Comment by michael-o** [comment]
@thc202 Thanks, missed that in the interactive add.

**Comment by michael-o** [comment]
One would also need to change the `@since` if we backport this to 4.5.x.

**Comment by ok2c** [comment]
@michael-o Ideally `RequestUserAgent` should be removed from the message processing chain entirely but looks good enough to me.

**Pull request merged**
