### PR TITLE
Use 'arm64' instead of 'arm64-graviton2'

### PR DESCRIPTION
**Pull request by martin-g**
The Graviton2 builder is available only on travis-ci.com. Apache uses travis-ci.org

Install Maven explicitly because it is not pre-installed on the ARM64 image for Trusty

Related-to: https://github.com/apache/httpcomponents-client/pull/265

### CODE REVIEW

**Comment by ok2c** [comment]
@martin-g I must admit I no longer understand what is going on in the Travis CI config. Please confirm everything works as intended now.

**Comment by martin-g** [comment]
Something is still not quite OK.
TravisCI has some differences between their .com and .org offering.
At https://travis-ci.com/github/martin-g/httpcomponents-core (my fork uses .com) everything is green
httpcomponents-core-travis-ci com

But at travis-ci.org the jobs look like before this PR ...
httpcomponents-core-travis-ci org

I'll try to find what could be the reason!

**Comment by martin-g** [comment]
My mistake! I was comparing -core against -client.
Everything looks OK at https://travis-ci.org/github/apache/httpcomponents-core !

**Comment by martin-g** [comment]
But -client has a new kind of failure on amd64 (https://travis-ci.org/github/apache/httpcomponents-client/jobs/741642674):

```
TestHttp1Reactive>AbstractHttpReactiveFundamentalsTest.testSequentialGetRequests:96->AbstractHttpReactiveFundamentalsTest.publisherToString:267->AbstractHttpReactiveFundamentalsTest.publisherToByteArray:279 » Runtime
```
Looking into it!

**Comment by martin-g** [comment]
I've re-run the build several times on my TravisCI project and all jobs pass.
Could you please run a new build at https://travis-ci.org/github/apache/httpcomponents-client ?

**Comment by ok2c** [comment]
@martin-g It is a known issue with a race condition in the reactive bindings. It should have been fixed in HttpCore. For now I will re-run the failing job.

**Comment by martin-g** [comment]
The build passed this time - https://travis-ci.org/github/apache/httpcomponents-client/builds/741642673!

**Comment by ok2c** [comment]
@martin-g All is well that ends well.

**Comment by Yikun** [comment]
@martin-g Friendly note, the `travis-ci.org` would be closed down in the end of 2020[1][2], I think the apache travis  should be switched to `travis-ci.com`.

[1] https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com
[2] https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by martin-g** [comment]
@Yikun I've asked Apache Infra at Slack and @Humbedooh told me that TravisCI stuff will do the migration at some point. 
Apache uses a paid plan at TravisCI and this means their stuff will help us migrating the repos.
Hopefully this will happen soon and all these differences between .org and .com will be in the past!

**Comment by Yikun** [comment]
@martin-g Cool, that's a good new, thanks for the info.

**Pull request merged**
