### PR TITLE
Method to check if the connection manager has been shut down and is closed or not.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Comment by ok2c** [comment]
@arturobernalg What about the async connection manager? What is the use case for this extra interface method? Do we really need it?

**Comment by arturobernalg** [comment]
> @arturobernalg What about the async connection manager? What is the use case for this extra interface method? Do we really need it?

HI @ok2c 
Agree that we need the same implementation on async connection manager. IMO its logical and necessary have a method in connections manager class a checker of the connections state.
TY

**Comment by ok2c** [comment]
> IMO its logical and necessary have a method in connections manager class a checker of the connections state.

@arturobernalg Why? What would be the use case?

**Comment by arturobernalg** [comment]
> > IMO its logical and necessary have a method in connections manager class a checker of the connections state.
> 
> @arturobernalg Why? What would be the use case?

it seemed logic have a method to check if the connections is still valid. Make it private?

**Comment by ok2c** [comment]
@arturobernalg you see, usually one closes the pool and then just throws it away. I do not see any use for this method outside the unit test. That is why I would not change the public APIs.

**Comment by arturobernalg** [comment]
> . That is why I would not change the public APIs.

HI @ok2c 
I see,  now I understand your point.  no need it make it public. WDYT private?  I  changed it private method, feel free   close the PR if you believe there is no need it.
TY

**Comment by ok2c** [comment]
@arturobernalg Feel free to keep them public in implementation classes or make them package private. Just make sure you make symmetric changes to the async conn manager as well.

**Comment by arturobernalg** [comment]
> @arturobernalg Feel free to keep them public in implementation classes or make them package private. Just make sure you make symmetric changes to the async conn manager as well.

Hi @ok2c 
Just to double check. When you say async conn manager, you mean to `PoolingAsyncClientConnectionManager.java`

**Comment by ok2c** [comment]
> Just to double check. When you say async conn manager, you mean to `PoolingAsyncClientConnectionManager.java`

@arturobernalg Yes.

**Comment by arturobernalg** [comment]
> > Just to double check. When you say async conn manager, you mean to `PoolingAsyncClientConnectionManager.java`
> 
> @arturobernalg Yes.

Great @ok2c 
changes are applied
TY

**Pull request merged**
