### PR TITLE
Add Zstd support to ContentCompressionExec.

### PR DESCRIPTION
**Pull request by arturobernalg**
This update allows automatic selection of Zstd as a compression algorithm when available.

### CODE REVIEW

**Comment by garydgregory** [comment]
Why not do this through Commons Compress?

**Comment by arturobernalg** [comment]
> Why not do this through Commons Compress?

In general  keep it simple. Adding a direct dependency on the Zstd library is a straightforward way to enable ``'Zstd' compression without the overhead of an additional module.

**Comment by ok2c** [comment]
@arturobernalg [Zstd](https://github.com/luben/zstd-jni#zstd) appears to be [BSD Licensed](https://github.com/luben/zstd-jni/blob/master/LICENSE). It _should_ be compatible with ASLv2 but I am afraid this needs to be double-checked. 

Why indeed not using Apache Compress if it provides compatible compression codec?

**Comment by garydgregory** [comment]
Hi all,

Commons Compress depends on the same lib BUT provides a facade API for all its archive and compressed file formats.

**Comment by ok2c** [comment]
> Hi all,
> 
> Commons Compress depends on the same lib BUT provides a facade API for all its archive and compressed file formats.

@garydgregory Got it. Thank you.

**Comment by arturobernalg** [comment]
> @arturobernalg [Zstd](https://github.com/luben/zstd-jni#zstd) appears to be [BSD Licensed](https://github.com/luben/zstd-jni/blob/master/LICENSE). It _should_ be compatible with ASLv2 but I am afraid this needs to be double-checked.
> 
> Why indeed not using Apache Compress if it provides compatible compression codec?

Well, my initial approach was to directly integrate the Zstd library to provide a  direct and potentially efficient solution. I see what i can do.

Thank you

**Comment by ok2c** [comment]
@arturobernalg Could you please change the target branch to `master` so I could delete obsolete `5.4.x`?

**Pull request closed without merging**
