### PR TITLE
scm-publish to /components/httpcomponents-client-5.0.x/LATEST

### PR DESCRIPTION
**Pull request by hboutemy**
update scm publish location to better show publication to staging of generated documentation in an unversioned LATEST directory

upcoming website PR will provide the glue of this staging documentation to its released/versioned copy and the main unversioned site

### CODE REVIEW

**Comment by ok2c** [comment]
@hboutemy `mvn scm-publish:publish-scm` fails for me. The command appears to have failed to create the target URL.

The target URL also looks wrong to me. It is `https://svn.apache.org/repos/asf/httpcomponents/site/components/httpcomponents-core-5.1.x/LATEST/` but should not it be `https://svn.apache.org/repos/asf/httpcomponents/site/httpcomponents-core-5.1.x/LATEST/ `?

```
[INFO] ----------< org.apache.httpcomponents.core5:httpcore5-parent >----------
[INFO] Building Apache HttpComponents Core Parent 5.1-beta3-SNAPSHOT      [1/5]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-scm-publish-plugin:3.0.0:publish-scm (default-cli) @ httpcore5-parent ---
[INFO] Remote svn url https://svn.apache.org/repos/asf/httpcomponents/site/components/httpcomponents-core-5.1.x/LATEST/ does not exist: creating.
[INFO] Executing: /bin/sh -c cd '/tmp/scm5570229970506090774tmp' && 'svn' '--non-interactive' 'mkdir' '--parents' 'https://svn.apache.org/repos/asf/httpcomponents/site/components/httpcomponents-core-5.1.x/LATEST//' '--file' '/tmp/maven-scm-692688204.commit'
[INFO] Checking out the pub tree from scm:svn:https://svn.apache.org/repos/asf/httpcomponents/site/components/httpcomponents-core-5.1.x/LATEST/ into /home/oleg/src/apache.org/httpcomponents/httpcore-5.x/target/scmpublish-checkout
[INFO] Executing: /bin/sh -c cd '/home/oleg/src/apache.org/httpcomponents/httpcore-5.x/target' && 'svn' '--non-interactive' 'checkout' 'https://svn.apache.org/repos/asf/httpcomponents/site/components/httpcomponents-core-5.1.x/LATEST/' '/home/oleg/src/apache.org/httpcomponents/httpcore-5.x/target/scmpublish-checkout'
[ERROR] Failed to check out from SCM: The svn command failed. svn: E170000: URL 'https://svn.apache.org/repos/asf/httpcomponents/site/components/httpcomponents-core-5.1.x/LATEST' doesn't exist

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache HttpComponents Core Parent 5.1-beta3-SNAPSHOT FAILURE [  4.554 s]
[INFO] Apache HttpComponents Core HTTP/1.1 ................ SKIPPED
[INFO] Apache HttpComponents Core HTTP/2 .................. SKIPPED
[INFO] Apache HttpComponents Core Reactive Extensions ..... SKIPPED
[INFO] Apache HttpComponents Core Integration Tests 5.1-beta3-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.177 s
[INFO] Finished at: 2021-01-30T10:15:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:3.0.0:publish-scm (default-cli) on project httpcore5-parent: Failed to check out from SCM: The svn command failed. svn: E170000: URL 'https://svn.apache.org/repos/asf/httpcomponents/site/components/httpcomponents-core-5.1.x/LATEST' doesn't exist
```

**Comment by michael-o** [comment]
@ok2c That targel URL is correct:

* `hc-site` comes first, all other projects land in components. They will be inlined by symlinks later.
* The error occurs because an old Maven SCM version is used and https://issues.apache.org/jira/browse/SCM-748 isn't included.
* All staging content lands in `LATEST` which is then copied with Subversion to production.

@hboutemy Why is there no archives-*`?

[This](https://maven.apache.org/developers/website/deploy-component-reference-documentation.html) resource rescribes the structure.

**Comment by hboutemy** [comment]
you'll probably have to create the base directories in svn by hand to initiate the structure, without waiting for SCM-748

don't forget to merge apache/httpcomponents-website#9 , or the structure will be deleted on next website publication before the PR merge

> Why is there no archives-*`?

I did not use strictly same structure as Maven, because HTTP Components is simpler: the `httpcomponents-core-5.1.x/` branch directory can contain contain `LATEST/` and every version directory as direct `${version}/`, no need for a `xxx-archives/` directory

**Comment by hboutemy** [comment]
you need to run `svn mkdir --parents https://svn.apache.org/repos/asf/httpcomponents/site/components/httpcomponents-core-5.1.x/LATEST/ -m "prepare documentation directory"` , because the scm-publish currently only can create one level of directory

this command is necessary only once, to initialize the whole process, then you don't need to worry any more in the future

**Pull request merged**
