### PR TITLE
feature/improve-tests-for-restrictedobjectinputstream

### PR DESCRIPTION
**Pull request by oloflarsson**
@ok2c Thank you for the quick merge of my previous pull requests. It in fact happened much faster than I expected. Was expecting some feedback and iterations 😄. In this pull request I have improved the testability of the whitelist and added a bunch of unit tests.

I took some inspiration from this blacklist: https://github.com/ikkisoft/SerialKiller/blob/master/config/serialkiller.conf

Notably these unit tests would catch a future addition of vulnerabilities in "org.apache.commons.collections..." which might be good to avoid hypothetical future mistakes.

Also we can now feel more certain the regexes do what I intended them to. Looks like they did (this pull request does not change them), but better write some tests to be on the safe side.

### CODE REVIEW

**Comment by ok2c** [comment]
@oloflarsson I can fold these changes into the previous commit.

**Comment by oloflarsson** [comment]
> @oloflarsson I can fold these changes into the previous commit.

Not sure I really understood what you meant but personally I would not rebase, but rather merge and keep the commit as is.

But I don't have a strong opinion on the matter 😄
Use whichever merging strategy you feel is best 👍

**Comment by ok2c** [comment]
@oloflarsson I profoundly dislike noisy commit history (though I admit not everyone shares my opinion).  I squashed those two logically related commit you have authored into a single one.

**Comment by michael-o** [comment]
I strongly agree with @ok2c . Intermediate work is just noise.

**Comment by oloflarsson** [comment]
Superb, thanks for pulling this 👍.
Have a nice weekend 😄!

**Pull request merged**
