### PR TITLE
CredSSP implementation, NTLM engine reworked

### PR DESCRIPTION
**Pull request by semancik**
I have also significantly improved NTLM implementation in the HTTP client. It is not better aligned with Microsoft specifications and it supports more protocol options. I had to do it because CredSSP requires NTLM support for GSS API wrapping/unwrapping. So I have implemented it. The description, motivation and limitations are in the source code javadoc.

The code is tested with several different Windows servers.

### CODE REVIEW

**Comment by ok2c** [comment]
Radovan,
NTLM used to be legal a legal minefield in the past. I still feel a bit uncomfortable just pulling in code related to Microsoft proprietary protocols without some due diligence. Was this change set produced under an employment contract and if so would your employer be willing to sign ASF [Corporate CLA](https://www.apache.org/licenses/#clas)?

**Comment by semancik** [comment]
I have used public Microsoft documentation released as Microsoft Open Specifications:
https://msdn.microsoft.com/en-us/library/cc236621.aspx
https://msdn.microsoft.com/en-us/library/cc226764.aspx
AFAIK, there should be no issue as Microsoft quite specifically provides these documents to allow third-party implementations. But I'm not a lawyer and the details are not entirely clear to me.

When it comes to my employer, I'm in fact self-employed. I'm already Apache committer and I have signed the agreement.  Does that count?

**Comment by ok2c** [comment]
The issue has been discussed with ASF legal ([see LEGAL-80](https://issues.apache.org/jira/browse/LEGAL-80?jql=project%20%3D%20LEGAL%20AND%20text%20~%20NTLM)). Given you are an existing ASF committer there should be no reason to not proceed. However, we still need to decide upon whether it can be added to 4.5 or we have to start 4.6 cycle in order to include this feature.

**Comment by bostko** [comment]
@semancik @ok2c WDYT about putting links to msdn specification in Java docs?

**Comment by semancik** [comment]
Done. References added.

**Comment by DaddyWri** [comment]
Hi @semancik,

I wrote the original NTLM implementation and wanted to review your changes, but you changed the formatting.  This is problematic both because it makes the diff hard to read and also because it violates the HttpComponents style checks and will thus not build without modifications.

**Comment by semancik** [comment]
The build worked fine for me. I have spend a lot of time fighting with checkstyle and make sure that it is satisfied. I have absolutely hated it, but I have done it. I have tried to find any description of coding conventions on project web site. But I have failed. Maybe because the it is incredibly hard to find almost anything on the site? Therefore I have used settings recommended by another Apache project. I have somehow assumed that Apache Java projects are used to the same coding conventions. Excuse me if I was wrong. However, I have spent a lot of time improving implementation of this nightmarish protocol. I really do not have more energy left reformatting the code once again. So, take it or leave it. I'm OK either way.

**Comment by DaddyWri** [comment]
Hi @semancik, the Apache standard can be overridden on a group-by-group basis, but the global standards are as follows:

- 4 spaces for each indent, no tabs
- braces in this style:
if {
} else {
}
- single space after commas in functions
- no spaces after or before parens, e.g. "( 1, 2 )"

This project's checkstyle is pretty rigorous but does not enforce all of the Apache standards.
It is indeed a challenge to work with, but is pretty self-explanatory when it finds a problem.

More importantly, it's just simply impossible to read diffs that include global reformatting.  I therefore discourage people from reformatting as a matter of course because it does make unnecessarily hard to evaluate submissions.  I'm not sure why you felt it necessary to *change* the style that was in place, but I have plodded through the diff, as it is, and if others agree it's acceptable in the current form, I will defer to that.

**Comment by semancik** [comment]
I haven't reformatted the code on purpose. I was fighting with checkstyle, which got incredibly annoying during the development. I have wasted a lot of time with that. So I have applied IDE autoformatting with my Apache settings. As that fixed the checkstyle I haven't explored any further. As I haven't seen any explicit statement about code conventions on the site I have assumed that I'm doing the right thing. Honestly, I haven't thought for a second that there may be several incompatible code conventions in Apache Foundation. OK, now I know. One learns every day, obviously. Anyway, the code is here. If you feel like reformatting then please go ahead. But I won't do it. I do not think that it is fair to expect people to follow rules that the project does not even bother to state (or that cannot be found on the website even if I specifically look for it).

**Comment by ok2c** [comment]
@DaddyWri Karl, Do you think you could review changes to NTLMScheme and just ignore the rest? We could incorporate those changes if they make sense to you and leave the rest.

**Comment by DaddyWri** [comment]
@ok2c I reviewed the entire diff and did not find any obvious problems.  As I said, it's easy to miss something though.  I'm reasonably happy if you want to commit it.

**Comment by ok2c** [comment]
@DaddyWri I am not feeling comfortable committing code that we are not able to maintain properly and the original contributor is unwilling to put any extra work into.

**Comment by DaddyWri** [comment]
@ok2c The changes to the NTLMScheme itself are relatively minor -- I think.
What I think we should do is reformat the submission and get a cleaner diff that way and then we can decide.

As for the new functionality, I agree we would do better to have someone on board longer term who understands it before committing it.  Having said that, it does not appear to be terribly complicated, but it doesn't have any tests even and that's a concern.  I'd volunteer to write some but I think we'd do far better to have the original author construct them, and I have been extremely pressed for time of late as well.

**Comment by DaddyWri** [comment]
@ok2c It also looks like you've migrated fully to git since I last worked on trunk on this project?  My git-fu isn't good enough to set up a branch with these changes for local evaluation -- perhaps you can give me some hints as to the best way to do that?

**Comment by DaddyWri** [comment]
@ok2c Ah, my bad - it's still in svn, just moved to new places.  Modifying the patch now.

**Comment by DaddyWri** [comment]
@ok2c  I had a long look at the NTLMEngineImpl changes.  Basically:
- Trace level debug support, which I recommend we remove because it is quite unsecure if enabled;
- For the CipherGen embedded cipher class, no substantive changes were made at all, just method and member variable renaming and formatting; I recommend we don't include any of these, since they add noise and no value;
- NTLMEngineImpl is now stateful and contains the history of all messages, and that's basically necessary to allow signing and sealing.  There must be considerable changes elsewhere to allow for this change in flow, which I have not looked at yet;
- Signing and sealing code, which constitutes the major addition to the engine itself.  I recommend we take those changes provided unit tests are developed for them.  There are a number of situations where signing and sealing support would allow future extensions to be worked in.  I also think it would be good to consider taking the CredSSP implementation, once it is in form to do so.

As for timing -- since it appears that Mr. Semancik has no further interest in this work, it's likely to be a while before I can do it.  Also, a trunk commit won't do much good for a backport to the 4.5.x branch since everything has moved, although with some effort a back patch might be developed.

I really wouldn't be concerned about proprietary legal problems; that ship sailed more than 15 years ago, and as Mr. Semancik points out, all of these specs are public now, and have been for more than a decade.

**Comment by ok2c** [comment]
@DaddyWri I leave this patch at your mercy. You are the only person on the project both capable and willing to put some effort into NTLM related code, therefore your opinion matters most. Do not worry about branching. I'll take care of merging the code into all active branches. Should we decide to include this code it will likely go into the new 4.6.x branch

**Comment by semancik** [comment]
My (not so humble) opinion is that the original contributor have put a lot of extra work already. The original contributor is just not willing to waste time. What is the real problem here? Is it that difficult to reformat the code when you already have the project formatting settings in your IDE? I do not have that. And I'm not willing to waste few hours looking up the setting and applying them just for this specific project. Even considering that you are not willing to put any "extra work" to the project by putting a reference to coding conventions to a project web site - or even a link to the source code. I'm sorry if this sounds harsh. I would just like to let you know how one of contributors submitting a non-trivial contributions feels about this. For the sake of future contributions to the project.

**Comment by semancik** [comment]
Another note: if you remove trace devel then there will be no way how to debug the code. I think I have made that quite clear in the comments. The first thing to know about CredSSP is that it is usually TLS-in-TLS protocol and there is no way how to diagnose the issues using a packet sniffer or any similar tool. The devel trace is only real option if you want to have the implementation maintainable. I suggest you have a look at MS-CSSP and not just consider the NTLM part in isolation. In fact it is not easy to enable the devel trace by mistake. So what is the point? You are all the rage about how formatting is an obstacle to maintenance. And that can be easily fixed. And then you are suggesting to remove one of the things that make maintainability possible? I'm sorry, but I do not really get it.

**Comment by ok2c** [comment]
@semancik Try contributing to a larger ASF project such as CXF that impose _very_ strict style requirements and conformance with static code analysis rules and then come back. HC style check barely requires _anything_ beyond trivial whitespace discipline and certain basic import rules. Yet you have spent more time bitching about the style check than it would have taken it to reformat the patch

**Comment by semancik** [comment]
I'm OK with adapting to a coding conventions. I have done that for several projects. But I would like to know the conventions from the beginning. I have adapted my contributions to the checkstyle that you have set up - even if that was costing a lot of my time. I have adapted to conventions that I believed are applicable to your project (even if I have that formatting style personally). I have already done all of that. But, it turns out, I have used wrong conventions. And why is that? Because I could not find anything about your coding conventions on your website. I could not even find link to the source code on your website. Therefore look at that from my point of view: I have done all that I could do adapt to your project. And all I get for that is criticism. That isn't really a reason to be happy about my contribution. That is not a good motivation to put any extra work in that, is it?

**Comment by DaddyWri** [comment]
@semancik It may have escaped your notice, but all of us are volunteers here.  I for one have a very busy life and am involved in many projects, including this one, that are wholly unrelated to my day job.  I've been working on your patch for about 4 hours already and I'm nowhere near done yet.  This is time I don't have other than what I have stolen from sleep.

I'm not pleased by the kind of attitude I'm seeing here; I can assure you that my request was not casual; I really *cannot* figure what you've actually done without reformatting the submission first.  I tried to help you understand why your approach makes it hard for patch integrators, but instead you've been responding with anger and complaints.

If you think you've just been misunderstood, then by all means let us start over.  If you want to work cooperatively to help us get your patch integrated, please show that you are willing to do that.  It's not so simple as just accepting the merge, because the merge goes into trunk first (and thus your patch won't even align with the source files that are there and I had to address that first off).

**Comment by semancik** [comment]
I'm willing to work cooperatively if you are willing to work cooperatively. Please update your website. Please put a link to the source code, coding conventions and IDE settings there. Then I can consider reformatting the code. But I will *not* reformat the code just to see another criticism how the formatting is wrong again.

**Comment by ok2c** [comment]
@semancik do not change formatting of existing classes and you will be fine.

**Comment by semancik** [comment]
Yes. That was my first thought. But IDE is imposing a formatting for a new code whether you want it or not. E.g. default IDE setting will indent empty lines which will make checkstyle very unhappy. So I have applied IDE settings that I though were the right ones. As I've already described several times. But it looks like you do not want to understand. Which is really a pity. I though that you might be interested in what a new contributor needs to go through. But maybe I was wrong. Maybe the "community over code" is not applied to all projects ...
Anyway. Contribution is there. I have done my best to prepare it. Then I was criticised for not following rules that were not stated. Even then I've tried to cooperate. But it looks like this does not lead anywhere. If you are not willing to even do this small improvement on your website to guide other contributors then I do not see any point in spending more time on this. So, you have the code. Take it or leave it. I already have my solution working. I just wanted to play nice, I went the extra mile and prepared my code for contribution as well as I could. Now I'm afraid that was all just wasted time. I'm sorry for that. Really sorry. Goodbye.

**Comment by ok2c** [comment]
@semancik You were politely requested to reformat your code to reduce noise in the change set due to different formatting in order to make the changes easier to understand. This has nothing to do with the default style settings at all. If you cannot tweak your IDE to make it stop messing with formatting this is your problem. The  "community over code" principle equally applies to @DaddyWri and the rest of us. Goodbye.

**Comment by ok2c** [comment]
@DaddyWri Ignore HttpClient 5 entirely for now. Develop your code against 4.5 APIs either on GitHub or on a branch in SVN. I'll merge the changes to trunk once everything is ready.

**Comment by DaddyWri** [comment]
Ok, started.  There's a branch: branches/pull-66, with the NTLMEngineImpl changes proposed (as modified by me).  I'm going to start my day job now and will pick this up in the evening.

**Comment by DaddyWri** [comment]
The branch, by the way, now has everything in it except the NTLMScheme changes, which essentially did nothing more than deprecate the standard NTLMScheme, which was not a reasonable way of doing things.

- I haven't written any new tests yet; patches welcome if anyone wants to tackle this
- It looks like Mr. Semancik wanted to fundamentally change the NTLMEngine API, which of course is
  not going to be something that can be done for backwards compatibility reasons
- The NTLMEngine itself is now stateful, as discussed before; this approach doesn't impress me as being
  a good idea, so I've made the methods that care about the previous NTLMMessages in the state be
  explicit arguments to the Type3Message constructor (at least one such variant)
- My thought is that the CredSspScheme should do the job of keeping track of previous messages, since
  it has to keep much state anyway, and then we can rip out the new statefulness of the NTLMEngine
  since it doesn't really belong there
- Much of the packing of new packets, though, should be moved into NTLMEngineImpl

**Comment by DaddyWri** [comment]
Ok, NTLMEngineImpl is now back to being stateless.

**Comment by DaddyWri** [comment]
Need to add CredSsp unit tests, and ask somebody to try it out, but then I think the branch might be ready to commit back to 4.5.x.

**Comment by DaddyWri** [comment]
Started working on the tests.  Did the following:

(1) Changed CipherGen so that it accepts a Random and long time value as arguments, so that tests can be made repeatable;
(2) Added packet byte value checks to be sure that the Type1 and Type3 responses don't change without us knowing.

Still to do: test NTLM fetch against an IIS-protected file, any Windows version,  This is necessary because the flags that are included now in the Type3Message are now the entire set of flags that come back in the Type2Message.  This might be correct as far as I know because when I implemented it year ago there was no description of what the Type3Message flags field should contain.  @semancik, when you said you "tried this against multiple Windows versions", did you try a straightforward NTLM file fetch to confirm that this still works?

If you haven't, and you would like to try this, you can check out the code at:

https://svn.apache.org/repos/asf/httpcomponents/httpclient/branches/pull-66

Please build and try it out, and let me know.  I no longer have ready access to a Windows system with IIS running, which limits my ability to exercise this code.

**Comment by DaddyWri** [comment]
@neykov Are you interested in helping to validate the final work? Do you have the Windows machines available to do this?  I'm happy to finish writing the tests, but I think the code needs to be revalidated against a Windows instance somewhere -- for both CredSsp AND NTLM fetch.

**Comment by neykov** [comment]
@DaddyWri yes, I can try it out. I'm usually using eval images generated with the help of https://github.com/RoboticCheese/boxcutter-windows, but also have a Windows machine to play with.

Are there any existing live tests for fetching files or shall I just write something quick & dirty to GET the file?

**Comment by DaddyWri** [comment]
@neykov Oh, I didn't know about this!  But yes, please write something quick and dirty to exercise an NTLM fetch against IIS with protected content, to be sure nothing broke.

**Comment by DaddyWri** [comment]
@neykov Looks like there's an error in the Type1Message builder; give me a moment to fix.

**Comment by DaddyWri** [comment]
@neykov Ok, fixed.

**Comment by neykov** [comment]
@DaddyWri Tried the `pull-66` branch and it's working great. I've logged the request-response exchange at https://paste.apache.org/1XC0.

**Comment by DaddyWri** [comment]
@neykov Great!  As soon as Oleg reviews it I'm ready to merge.

**Comment by neykov** [comment]
CredSSP works as well. Found a small issue if I don't specify a domain in `NTCredentials`:

```
Caused by: java.lang.NullPointerException
	at org.apache.http.impl.auth.CredSspScheme.encodeUnicode(CredSspScheme.java:569)
	at org.apache.http.impl.auth.CredSspScheme.createAuthInfo(CredSspScheme.java:490)
	at org.apache.http.impl.auth.CredSspScheme.authenticate(CredSspScheme.java:383)
	at org.apache.http.impl.auth.HttpAuthenticator.doAuth(HttpAuthenticator.java:239)
	at org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:218)
	at org.apache.http.impl.nio.client.MainClientExec.generateRequest(MainClientExec.java:224)
```

**Comment by DaddyWri** [comment]
What would you recommend we do in that case?  Default to empty string?

Karl

**Comment by DaddyWri** [comment]
I committed a null check and return of byte[0] to fix what you found.  Thanks!!

**Comment by neykov** [comment]
Any value seems to work, including the empty string.

**Comment by ok2c** [comment]
The original change set has been committed to SVN 4.5.x, 4.6.x and trunk (5.0). Please review and close

**Comment by neykov** [comment]
Awesome, great work @semancik, @DaddyWri, @ok2c.

**Comment by semancik** [comment]
CredSSP is needed in implementation of Microsoft WS-MAN protocols, especially WINRM. Kerberos does not solve the "second hop problem" (see https://docs.microsoft.com/en-us/windows/desktop/winrm/multi-hop-support). CredSSP seems to be the only viable solution. I do not like that myself. CredSSP is a terrible protocol, one of the worst I have ever seen. But it looks like there is no better (or less evil) approach.

**Comment by semancik** [comment]
Also please note that CredSSP implementation in the above pull request is already outdated. It won't work with recent Windows servers as Microsoft has changed the implementation. Due to the update of NTLM engine done after my pull request, my updated code no longer works with stock HTTP client. The working code is maintained in my fork: https://github.com/Evolveum/httpclient

Obviously, this form of cooperation is not possible. Firstly, it is very difficult to cooperate with HTTP client team. E.g. we cannot really agree on basic issues, such as whether implementation of inherently stateful protocols such as NTLM should be stateful or stateless (not to mention code formatting, but that in fact is not a real problem). And secondly, it probably does not make a lot of sense to keep implementation of ugly and exotic protocols such as CredSSP in the HTTP client core at all. Therefore a better way would be to have authentication methods pluggable. I think that should be the next milestone. Unfortunately, I won't be able to find the time for this in a near future. Therefore it looks like the only option for now is to maintain the fork - even though this is not a good way at all.

**Comment by ok2c** [comment]
@michael-o I would be in favor of removing `CredSSP` auth scheme from our code base.

**Comment by semancik** [comment]
Actually, I would also be in favour of removing the CredSSP code from HTTP client. It makes no sense to pollute HTTP client with outdated and unmaintained code. And given current situation there is no practical way how to maintain that code in HTTP client core.

**Comment by semancik** [comment]
@michael-o My understading is that it cannot be achieved by Kerberos for all the cases. E.g. if you need device that is not part of the domain to access WinRM service. That is often the case for monitoring or management infrastructure (such as IDM).
Of course we are managing servers with "custom" code via SOAP. That's what WinRM client is, isn't it?
As for the disagreement: the original NTLM "engine" in HTTP client was stateless. I guess that it was stateless because it was only partial implementation done long before Microsoft opened up the specifications. The implementation was a simple 3-message exchange which was not that hard to implement in a stateless way. However, CredSSP needs full NTLM implementation with wrapping (a.k.a. "encryption") capability. Therefore I have implemented it. In a stateful way, which was quite an obvious choice. But my contribution was re-engineered to stateless implementation once again. Without any explanation. That was the point that I have decided that the cooperation won't work.

**Comment by semancik** [comment]
@michael-o Of course, my first choice was to use the plugging mechanism for auth scheme. But there were several problems. I needed CredSSP to take precedence over NTLM during auth negotiation. And I needed updated NTLM implementation (as explained above). I could not achieve any of those with existing code. I was trying to start communication on the mailing list. But there was no reaction. Therefore I did my best with the information that I had at the time. Maybe some time there will be a time to revisit this. But for now my fork does the job. It is a shame that we as members of open source community (and especially Apache foundation) cannot really communicate. But obviously, that's the way how it is.

**Comment by DaddyWri** [comment]
The NTLM engine changes were indeed integrated, so I don't know what you're talking about in that regard.

**Comment by ok2c** [comment]
@michael-o `CredSsp` stuff dropped with 03de3ab16c56cd0604a8a8d61b3a390ee7e791c5

**Comment by ok2c** [comment]
@michael-o The contributor was kindly requested to reformat his code to make it easier for us to review the changes. His reaction can be seen here  https://github.com/apache/httpcomponents-client/pull/66#issuecomment-286491017.

**Comment by semancik** [comment]
@ok2c The contributor agreed to reformat his code. But he also kindly asked for code formatting rules to be documented. Maintainers refused.

**Comment by michael-o** [comment]
@semancik

> E.g. if you need device that is not part of the domain to access WinRM service. That is often the case for monitoring or management infrastructure (such as IDM).

Agreed, but the user account has to be in the Active Directory otherwise even NTLM won't work.

> As for the disagreement: the original NTLM "engine" in HTTP client was stateless. I guess that it was stateless because it was only partial implementation done long before Microsoft opened up the specifications. The implementation was a simple 3-message exchange which was not that hard to implement in a stateless way. However, CredSSP needs full NTLM implementation with wrapping (a.k.a. "encryption") capability. Therefore I have implemented it. In a stateful way, which was quite an obvious choice. But my contribution was re-engineered to stateless implementation once again. Without any explanation. That was the point that I have decided that the cooperation won't work.

That's pretty sad. I have checked the entire discussion and it was changed back and forth, but NTLM must be stateful. Everything does not make sense to me.

> I needed CredSSP to take precedence over NTLM during auth negotiation. And I needed updated NTLM implementation (as explained above). 

That's partially true. What you can do is have the NTLM engine updated and keep the CredSSP for youself why settting and auth scheme registry. This would have solved your problem.

The PR itself wan't just granular enough, I have have rejected it too and requested to spilt in several ones as I do for all Maven PRs.

**Comment by ok2c** [comment]
@semancik The code formatting conventions are available and well documented. See https://www.oracle.com/technetwork/java/codeconventions-150003.pdf. This was pointed out to you.

**Comment by ok2c** [comment]
@michael-o `NTLMEngine` doe not _have_ to be stateful because `AuthScheme` instances are stateful by design.

**Comment by semancik** [comment]
@ok2c Having stateless NTLM engine will complicate the implementation. In fact, the correct implementation would use GSSAPI, not having NTLM engine as a separate module in HTTP client. And good luck with stateless use of GSSAPI.

**Comment by semancik** [comment]
@ok2c Would be that hard to put the link to the formatting convention on project home page? That was the first thing that I have looked for. Different projects have different conventions. A have used conventions used by another Apache project. And I have (wrongly) assumed that such conventions apply to all Apache projects. Which meant I had additional work to do to reformat the contribution - even though I made reasonable attempts to avoid that work. What I wanted is for others not repeat make my mistake. I was willing to reformat the code (again). But there was absolutely no will to do even this simple thing of mentioning formatting rules on project page. Well, given all the other circumstances further cooperation seemed like a pointless path to take.

**Comment by semancik** [comment]
@ok2c I'm sorry, but once again I have to conclude that there is no will to understand what I'm trying to say. There is no point in continuing this conversation. Again.

**Comment by semancik** [comment]
@michael-o I would gladly split the PR. I would even gladly modify it for better modularity. Given that HTTP Client has almost zero design documentation and given no responses to my mailing list messages I did the best I could. What I've got in return was complaints about wrong code formatting - given that I have did my best effort to check for formatting rules before I started the contribution, found none, then I used the (organizationally) closest definition that I have found. And even went through the pain of satisfying checkstyle plugin. And after all that frustration I've got into a fight that actually boiled down to whether code formatting rules should or should not be mentioned on project home page. I'm sorry, but all of this seems to be completely ridiculous to me.

**Pull request closed without merging**
